/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#000000",
        "primary-container": "#131b2e",
        "on-primary": "#ffffff",
        "on-primary-container": "#7c839b",
        "primary-fixed": "#dae2fd",
        "primary-fixed-dim": "#bec6e0",
        "on-primary-fixed": "#131b2e",
        "on-primary-fixed-variant": "#3f465c",
        "secondary": "#006c4a",
        "secondary-container": "#82f5c1",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#00714e",
        "secondary-fixed": "#85f8c4",
        "secondary-fixed-dim": "#68dba9",
        "on-secondary-fixed": "#002114",
        "on-secondary-fixed-variant": "#005137",
        "tertiary": "#000000",
        "tertiary-container": "#2a1700",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#b87500",
        "tertiary-fixed": "#ffddb8",
        "tertiary-fixed-dim": "#ffb95f",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-fixed-variant": "#653e00",
        "surface": "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "on-surface": "#0b1c30",
        "on-surface-variant": "#45464d",
        "inverse-surface": "#213145",
        "inverse-on-surface": "#eaf1ff",
        "outline": "#76777d",
        "outline-variant": "#c6c6cd",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "background": "#f8f9ff",
        "on-background": "#0b1c30"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "space-2": "0.125rem",
        "space-4": "0.25rem",
        "space-6": "0.375rem",
        "space-8": "0.5rem",
        "space-12": "0.75rem",
        "space-16": "1rem",
        "space-20": "1.25rem",
        "space-24": "1.5rem",
        "space-32": "2rem",
        "space-48": "3rem",
        "gutter-desktop": "1rem",
        "gutter-mobile": "0.75rem",
        "container-max": "1240px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "display-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-md": ["Inter"],
        "headline-sm": ["Inter"],
        "price-lg": ["Inter"],
        "price-md": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "label-bold": ["Inter"],
        "badge": ["Inter"]
      },
      fontSize: {
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "price-lg": ["22px", { lineHeight: "28px", fontWeight: "700" }],
        "price-md": ["18px", { lineHeight: "24px", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-bold": ["13px", { lineHeight: "18px", fontWeight: "600" }],
        "badge": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
